Independent egl
baldurk/renderdoc pull request #1549
Opened 2019-10-10 14:41 UTC by afrantzis

## Description

Make EGL indepedent of GLES, and replace code dependencies on GLES with EGL dependencies where it makes sense (e.g., wayland support).

2019-10-10 15:02 UTC, baldurk requested changes
Thanks for this, it looks good to me. I've left a few notes on minor fixes for different configurations (Android/Windows) which this change is a bit sensitive to.

2019-10-10 15:02 UTC, baldurk commented on CMakeLists.txt
>  if(ANDROID)
We should force on `ENABLE_EGL` on android, the same as we do for `ENABLE_GLES`.

2019-10-10 15:02 UTC, baldurk commented on renderdoc/driver/gl/egl_platform.cpp
> +    EGLBoolean supportsGL = EGL.BindAPI(EGL_OPENGL_API);
I'm quite worried about this breaking on Android, because it's an extremely unreliable/unpredictable platform so I don't trust the query to work there. Can you please add an extra safety compile-time check for Android like this:

```cpp
#if ENABLED(RDOC_ANDROID)
    return false;
#else
    // ...
#endif
```

2019-10-10 15:02 UTC, baldurk commented on renderdoc/driver/gl/gl_common.h
> +  typedef void *EGLConfigPtr;
If we don't have the distinction of these being "whatever GLES uses" anymore, it might be easier to use `EGLDisplay` etc directly, and just typedef them to `void *` only in the `#if !defined(RENDERDOC_SUPPORT_EGL)` case?

It should be fine either way but might make things easier when we really are using EGL types directly, rather than nominally pretending that the GLES types might not be EGL on some platforms.

2019-10-10 15:02 UTC, baldurk commented on CMakeLists.txt
> +    add_definitions(-DRENDERDOC_SUPPORT_EGL)
I can't leave a comment on lines which are nowhere near a change, so putting it here - this is one minor downside of the windows build not going through cmake: It doesn't pick up these feature defines like this. This is the only time they're even relevant for windows because the GL project is built with conditional code for whether each GL variant is supported.

Long story short - make sure to add `#define RENDERDOC_SUPPORT_EGL` into gl_common.h around line 50, in the `WIN32` pre-processor branch.

2019-10-11 11:33 UTC, afrantzis commented on CMakeLists.txt
>  if(ANDROID)
Done.

2019-10-11 11:33 UTC, afrantzis commented on renderdoc/driver/gl/egl_platform.cpp
> +    EGLBoolean supportsGL = EGL.BindAPI(EGL_OPENGL_API);
Done.

2019-10-11 11:33 UTC, afrantzis commented on renderdoc/driver/gl/gl_common.h
> +  typedef void *EGLConfigPtr;
Done.

2019-10-11 11:34 UTC, afrantzis commented on CMakeLists.txt
> +    add_definitions(-DRENDERDOC_SUPPORT_EGL)
Done.

2019-10-11 11:36 UTC, afrantzis commented
Thanks for the feedback! I have updated this PR with the requested changes (and a couple of other slight formatting changes).

2019-10-11 11:39 UTC, baldurk approved these changes

2019-10-11 11:39 UTC, merged