Fix constant buffer lookups with SM5.1 shader debugging
baldurk/renderdoc pull request #1699
Opened 2020-01-26 20:31 UTC by skarolewics

This fixes several issues related to constant buffers that I found while capturing/debugging D3D12:

- Constant buffers were stored in a flat array, so overlapping registers with different register spaces didn't work. Adding a constant buffer to the ShaderDebugTrace now uses the ShaderBindpointMapping to convert from a register/space to the identifier used by the shader.
- Constant buffers as instruction operands differ with SM5.1 - the data lookup is shifted by one index since the shader register is also specified.
- Constant buffer declarations now store the identifier (correlated to the order presented in the bytecode) to aid finding the correct buffer.
- Without reflection info, constant buffers appeared incorrect in the pipeline state viewer with D3D12. The size in float4s is stored by the declaration so that when guessing the reflection we have the appropriate buffer size.

2020-01-27 18:06 UTC, baldurk requested changes
I've left a few notes here, I think only the last one about needing to handle the missing index is significant - I'm not sure this change is going to handle arrays of constant buffers correctly.

I can see two ways of doing it: one where we have the array unrolled so that the base register is at `[i]` and then subsequent registers are at `[i+1], [i+2] ... [i+n-1]`. The other is to take advantage of the nest-ability of `ShaderVariable` and have constant buffer arrays have a root element which is the constant buffer array, then each element within that is a whole constant buffer struct.

2020-01-27 18:06 UTC, baldurk commented on renderdoc/driver/d3d11/d3d11_shaderdebug.cpp
> +      debugManager.GetBufferData(shader.ConstantBuffers[i], shader.CBOffsets[i] * sizeof(Vec4f), 0,
Should use `CBCounts` here too, so that constant buffers which are truncated (where supported) are accurately debugged.

2020-01-27 18:06 UTC, baldurk commented on renderdoc/driver/shaders/dxbc/dxbc_debug.cpp
> +            format, i, (uint32_t)c, trace.constantBlocks[i].members[c].name.c_str());
If we have a shader with only one cbuffer at slot 3, then in the SM5.0 case will this do the wrong thing? It formats using `i` as the first index which is always our 0-based flat index, but I think really what we want is `slot.shaderRegister` to be equivalent to the previous `dxbc->GetReflection()->CBuffers[i].reg` for 5.0.

We could pre-format the first part of `CB%u` or `cb%u` outside in a different way for each case either using `i` or `slot.shaderRegister`, then use that as a prefix string inside the loop.

2020-01-27 18:06 UTC, baldurk commented on renderdoc/driver/shaders/dxbc/dxbc_debug.cpp
> +  RDCERR("Cannot find cbuffer (c%u, space%u) in shader mapping", slot.shaderRegister,
Nit: should probably be `b%u` to match HLSL, not that I'd expect any confusion anyway.

2020-01-27 18:06 UTC, baldurk commented on renderdoc/driver/shaders/dxbc/dxbc_bytecode.cpp
> +        uint32_t numVecs = isShaderModel51 ? dcl.float4size : (uint32_t)dcl.operand.indices[1].index;
Not needed for this PR, but this would be a nice thing to add a test for. Ideally as a new test of reflection-guessing so that it can be expanded for other resource types & cases as necessary.

2020-01-27 18:06 UTC, baldurk commented on renderdoc/driver/shaders/dxbc/dxbc_debug.cpp
> +      uint32_t cbLookup = program->IsShaderModel51() ? indices[2] : indices[1];
We'll need to use `indices[1]` here somehow to select the cbuffer when dealing with cbuffer arrays.

2020-01-27 18:17 UTC, skarolewics commented on renderdoc/driver/shaders/dxbc/dxbc_bytecode.cpp
> +        uint32_t numVecs = isShaderModel51 ? dcl.float4size : (uint32_t)dcl.operand.indices[1].index;
Yeah there's a handful of SM5 vs SM5.1 things that I'd like to add tests for.

2020-01-28 04:07 UTC, skarolewics commented on renderdoc/driver/shaders/dxbc/dxbc_debug.cpp
> +            format, i, (uint32_t)c, trace.constantBlocks[i].members[c].name.c_str());
Verified with a quick test that you're correct. Fixed, and I'll include this scenario in a test in a later PR.

2020-01-28 06:55 UTC, skarolewics commented on renderdoc/driver/shaders/dxbc/dxbc_debug.cpp
> +  RDCERR("Cannot find cbuffer (c%u, space%u) in shader mapping", slot.shaderRegister,
Fixed

2020-01-28 06:55 UTC, skarolewics commented on renderdoc/driver/d3d11/d3d11_shaderdebug.cpp
> +      debugManager.GetBufferData(shader.ConstantBuffers[i], shader.CBOffsets[i] * sizeof(Vec4f), 0,
Fixed

2020-01-28 06:56 UTC, skarolewics commented on renderdoc/driver/shaders/dxbc/dxbc_debug.cpp
> +      uint32_t cbLookup = program->IsShaderModel51() ? indices[2] : indices[1];
Still looking into this, making some test cases.

2020-01-28 18:44 UTC, baldurk approved these changes

2020-01-28 18:44 UTC, merged