[imporove]renderdoc interceptor-lib can read Q regeisters in AArch64
baldurk/renderdoc pull request #2347
Opened 2021-08-18 03:52 UTC by new-TonyWang

Interceptor-lib cannot read Q regisiters in Huawei, and there were errors in Diagnostic Log, but no more now.

2021-08-18 09:12 UTC, baldurk requested changes
This library is no longer maintained upstream so I'm fine making this change here, but please tidy up the commit history to a single commit and explain what this change does and why in the commit message so that it can be seen clearly in future.

I've also made one note about a change that should be reverted.

2021-08-18 09:12 UTC, baldurk commented on .gitignore
> +.github
Please don't add anything to the .gitignore if it's not necessary for the change.

2021-09-01 02:54 UTC, new-TonyWang commented on .gitignore
> +.github
ok

2021-09-17 10:13 UTC, baldurk commented
Closing this due to lack of activity and no updates. If you would like to submit these changes again in future please open a new pull request after addressing the review feedback above.

2021-09-17 10:13 UTC, closed without merging