Add support 3d ASTC compressed textures
baldurk/renderdoc pull request #2388
Opened 2021-10-08 08:54 UTC by lfedorov

## Description

Some modern mobile games used 3d lightmaps in compressed formats, so right now RenderDoc can't collect them properly on GLES 2.0 / 3.0.
Added support NxNxN ASTC compressed textures (RGBA and SRGB8_ALPHA8). Small refactoring of existed code.

2021-10-08 09:00 UTC, lfedorov commented
Here is sample Android project with 3d ASTC texture to test PL: 
[app-debug_compressed_3d_texture.zip](https://github.com/baldurk/renderdoc/files/7309937/app-debug_compressed_3d_texture.zip)

2021-10-11 11:27 UTC, baldurk requested changes
I think this looks good, I've only noted one case where you shouldn't use `rdcarray` to avoid unnecessary heap allocations.

2021-10-11 11:27 UTC, baldurk commented on renderdoc/driver/gl/gl_resources.cpp
> +rdcarray<uint32_t> GetCompressedBlockSize(GLenum internalformat)
You should either use `rdcfixedarray` or else make a new struct with three members, as `rdcarray` will dynamically allocate its storage.

2021-10-11 13:31 UTC, lfedorov commented on renderdoc/driver/gl/gl_resources.cpp
> +rdcarray<uint32_t> GetCompressedBlockSize(GLenum internalformat)
Sure! Fixed.

2021-10-12 16:52 UTC, merged