full implementation of compute msaa-to-buffer
baldurk/renderdoc pull request #2515
Opened 2022-03-08 07:24 UTC by tuxerr

Deprecates the Vulkan MSAA->Array->Buffer codepath in favor of a compute-based, direct MSAA<->Buffer. This replaces all 4 functions, color and depth for load and store operations. 

Adds 4 vulkan-only shaders, ms2buffer/depthms2buffer/buffer2ms/depthbuf2ms (still fragment due to stencil write necessity). On serialize load, uploads the uploadBuf into a GPU-local buffer for read speeds (reading from the non-GPU-local buffer was crashing my NVIDIA GPU for SSBOs > 100Mb, which is easy to reach on D32S8, MSAA4x big textures). 

For depth-stencil buffers, the compute codepath outputs the data as interleaved (instead of the previous all-depth/all-stencil approach). 

This allows a single stencil fetch to be done instead of the 256 previous ones for GetTextureData(), which accelerates Quest2 D24S8 fetch by ~15x. Tested on Quest2 and NVIDIA, on various Unity D24S8 contents, and on Sascha Willems's deferred multisample demo with various formats. Also passes TextureZoo!

2022-03-08 15:13 UTC, baldurk requested changes
Thanks for this! I've left quite a few notes but I promise most of them are not that bad and pretty minor. There's a couple of places where I think this can be further simplified to make it cleaner, but overall this looks great and it's some quite squirrelly code even at the best of times.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/data/glsl/buffer2ms.comp
> +layout(push_constant) uniform multisamplePush
It's fine to make these vulkan-only shaders without GL ifdefs, but in that case I think it would be better to name them `vk_buffer2ms.comp` to be clear. Also in that case things like the `PRECISION` define are no longer needed since that's a GLES-only thing.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/data/glsl/depthbuf2ms.frag
> +      depth = D16ToFloat(data >> 16 & 0xFFFF);
You should make this `(data >> 16) & 0xFFFF` like you have below, mostly just because I don't remember or trust operator precedence rules in GLSL.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/driver/vulkan/vk_debug.cpp
> +  vkr = m_pDriver->vkCreateDescriptorPool(dev, &bufferPoolInfo, NULL, &m_MS2BufferDescriptorPool);
There's no reason to have a separate descriptor pool for this since we know statically how many descriptors we need in total.

Also unless you feel strongly otherwise it feels like it might be simpler to have a single descriptor set layout for all of these shaders - bindings 0 and 1 for sampled images, binding 2 for storage image, binding 3 for storage buffer. Since each variant only _statically_ uses the same subset, it should work out to the same code at update/binding time just with different binding points. Similar to how in the old code ms2array.comp didn't use binding 1 at all, it just used binding 0 for the source MSAA image and binding 2 for the storage array image.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/driver/vulkan/vk_debug.cpp
>                      {0, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1, VK_SHADER_STAGE_ALL, NULL},
Since the shaders are now vulkan only we can drop this to just `SAMPLED_IMAGE` descriptor and not need any dummy sampler binding.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/driver/vulkan/vk_replay.cpp
> +  SCOPED_TIMER("GetTextureData");
I'm not necessarily opposed to having a timer in here, but this might get quite spammy in the log for remote replay. Was this intentional or is this leftover from testing?

2022-03-08 15:13 UTC, baldurk commented on renderdoc/driver/vulkan/vk_replay.cpp
> +    vt->CmdFillBuffer(Unwrap(cmd), readbackBuf, 0, VK_WHOLE_SIZE, 0);
This shouldn't be necessary unless I misunderstand, as the buffer will be overwritten by the copy itself. This could be good to leave behind an RDOC_CONFIG option for debugging though perhaps.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/driver/vulkan/vk_replay.cpp
> +    m_pDriver->FlushQ();
Minor organisational thing - this code with the buffer barrier and submit & flush could be moved to be shared code after the `if(copyToBuffer) {}` as it's the same in both paths I believe? If we're in this path then we're setting `copyToBuffer` to false so it's effectively the same in that respect just not duplicated.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/driver/vulkan/vk_initstate.cpp
> +                                                             VK_BUFFER_USAGE_STORAGE_BUFFER_BIT};
Minor note - adding a trailing comma `,` onto structs like this will cause clang-format to not compact it, which is nice when it ends up a bit messy like this and the 'expanded' formatting is preferable.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/driver/vulkan/vk_initstate.cpp
> +          initialContents.mem = gpuUploadMemory;
This should mean you can delete the `img` member of `VkInitialContents` in `vk_manager.h`, as this was the only place it was used (together with the use below in `Apply_InitialState` which is also gone).

2022-03-08 15:13 UTC, baldurk commented on renderdoc/data/glsl/buffer2ms.comp
> +    imageStore(dstMS, ivec3(x0, y0, slice), sampleIdx, uvec4(data.x >> 0 & 0xFF, 0, 0, 0));
Another case to add brackets for precedence like `(data.x >> 0) & 0xFF`.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/data/glsl/depthbuf2ms.frag
> +  int textureSamples;
`textureSamples` seems to be the same as `numMultiSamples` and both it and `textureSlices` look to be unused currently.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/data/glsl/depthbuf2ms.frag
> +    uint idx = srcCoord.x + textureWidth * (srcCoord.y + (textureHeight * srcCoord.z));
This `idx` calculation looks like it's the same in all branches (which makes sense), so it would be good to pull it out of the ifs.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/driver/vulkan/vk_shader_cache.cpp
> +                        rdcspv::ShaderStage::Fragment),
These shaders will need feature checks - I think mostly the same as the previous ones at least `FeatureCheck::ShaderMSAAStorage | FeatureCheck::FormatlessWrite` for `Buffer2MSCS`, `FeatureCheck::SampleShading` for `DepthBuf2MSFS` and probably `FeatureCheck::NonMetalBackend` for all of them just to be safe. Since the other shaders are no longer used they should be removed too.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/driver/vulkan/vk_shader_cache.h
> +  DepthBuf2MSFS,
You'll also need to update the `IsArray2MSSupported` function, which is the same check (can we store to MSAA and write without format). The `IsMS2ArraySupported` function is unused and can probably just be deleted for now, until a time that it's needed.

2022-03-08 15:13 UTC, baldurk commented on renderdoc/driver/vulkan/vk_msaa_buffer_conv.cpp
> +        ObjDisp(cmd)->CmdDispatch(Unwrap(cmd), AlignUp(extent.width * extent.height, ms) / ms, 1, 1);
I think with a large texture this runs the risk of hitting dispatch size limits, since some low-end implementations only support I think around 64k in each dimension for a dispatch.

The easiest solution most likely is to change the compute shader to have a workgroup of 64 and divide by 64 here. You might want to make  both types of dispatches 1D perhaps to keep things simple? Then clamp the id in the shader so any 'leftovers' in the final workgroup don't do any out of bounds indexing.

2022-03-09 05:29 UTC, tuxerr commented on renderdoc/driver/vulkan/vk_replay.cpp
> +  SCOPED_TIMER("GetTextureData");
leftover, my bad.

2022-03-09 05:30 UTC, tuxerr commented on renderdoc/driver/vulkan/vk_msaa_buffer_conv.cpp
> +        ObjDisp(cmd)->CmdDispatch(Unwrap(cmd), AlignUp(extent.width * extent.height, ms) / ms, 1, 1);
good point, moved all shaders to 1D dispatches and added
```
  if(int(idx) >= maxInvocationID)
  {
    return;
  }
  ```
  to clamp the globalInvocation ID.

2022-03-09 05:30 UTC, tuxerr commented on renderdoc/driver/vulkan/vk_replay.cpp
> +    m_pDriver->FlushQ();
ah, good catch. merged.

2022-03-09 05:33 UTC, tuxerr commented on renderdoc/driver/vulkan/vk_initstate.cpp
> +                                                             VK_BUFFER_USAGE_STORAGE_BUFFER_BIT};
better? :-'

2022-03-09 12:10 UTC, merged