Hide invalid shader resources in pipeline state viewer since 1.24
baldurk/renderdoc pull request #2987
Opened 2023-07-19 12:18 UTC by hellokenlee

## Description

Since v1.24 after this commit 61fc2f82f20c966287173d561bffdd1711158e84.

The D3D12 pipeline state viewer keep showing useless shader resource which are not defined in shader source：

![Snipaste_2023-07-19_17-02-49](https://github.com/baldurk/renderdoc/assets/8079836/2ea92b57-e94b-4b6b-92c7-01bf8ae1bb42)
【 This is a capture of Unreal Engine. But the problem is showing on every d3d12 captuers.】

This problem is not showing in v1.23. This PR should fix this problem:
![Snipaste_2023-07-19_17-04-37](https://github.com/baldurk/renderdoc/assets/8079836/ec70b33e-1c4f-4a5a-890a-263d5337d269)

2023-07-19 12:35 UTC, baldurk commented
Can you please provide a reproducible test case that shows this problem?

2023-07-19 13:39 UTC, hellokenlee commented
Sure, the following capture of UE5 shows the problem, in event 498 for example.
( Due to Github's stupid file size and extension limitation, the default engine settings is changed to create a minimal rdc file, but it should be enough. The file is compressed in a 7z format. )
[UnrealEditorDefault.7z.zip](https://github.com/baldurk/renderdoc/files/12095535/UnrealEditorDefault.7z.zip)

2023-07-25 12:40 UTC, baldurk requested changes
Thanks for sharing the repro - I can see the problem that if there are more registers bound than used, the last binding will not properly be reset when searching for a new matching binding.

In this case I think the better fix is to set `bind = NULL` inside the if() on line 1157. That way if the loop doesn't find any matching binding it will handle it correctly from then on. Your change is slightly redundant and also still leaves `bind` set when it shouldn't be.

2023-07-26 03:09 UTC, hellokenlee commented
Okay, I see. The `bind` variable is the main variable used in following conditional statements. One more thing, should we set  `shaderInput = NULL` together or just leaves it set?

2023-07-26 09:23 UTC, baldurk commented
Yes resetting that to `NULL` as well should be fine, though it shouldn't be used without the corresponding `bind` but is best for safety to set them together.

2023-07-26 21:01 UTC, merged