Add D3D12 pixel history implementation
baldurk/renderdoc pull request #3164
Opened 2023-12-10 01:39 UTC by skarolewics

It is disabled by default but can be enabled in the config editor via D3D12/PixelHistory.

This is the last commit needed for testing and continued validation/improvement of D3D12 pixel history. There will be one follow-up commit to add an automated smoke test (similar to the Vulkan pixel history test).

2023-12-11 15:38 UTC, Zorro666 requested changes
Thank you for all your work on this - it is a great starting place.

One minor change to make the config option be developer only until the feature is more tested and robust.

I gave it a quick trial on a simple D3D12 draw triangle capture I have and it worked to get the per fragment colour but didn't appear to be correct at a per event i.e. the clear result was the wrong colour and the one fragment that touched the pixel didn't get updated correctly but the per fragment value was correct.

I have seen this before in the other API pixel history : it usually a quick fix which will can be the starting point after this PR and the follow up test PR is merged.

![image](https://github.com/baldurk/renderdoc/assets/39392/14d6ebdc-df33-4c32-8965-c202c06f0a14)

2023-12-11 15:38 UTC, Zorro666 commented on renderdoc/driver/d3d12/d3d12_replay.cpp
> +RDOC_CONFIG(bool, D3D12_PixelHistory, false, "BETA: Enable D3D12 pixel history support.");
For now perhaps can we make this be a developer only configuration option

i.e.

RDOC_DEBUG_CONFIG()

then it won't be available in stable released builds.

When the implementation has had more testing and updates then we can migrate it to a user option.

2023-12-11 15:38 UTC, Zorro666 commented on renderdoc/driver/d3d12/d3d12_replay.cpp
> +RDOC_CONFIG(bool, D3D12_PixelHistory, false, "BETA: Enable D3D12 pixel history support.");
and for consistency with other developer only options make the name be `D3D12_Debug_PixelHistory`

2023-12-11 16:48 UTC, baldurk commented on renderdoc/driver/d3d12/d3d12_replay.cpp
> +RDOC_CONFIG(bool, D3D12_PixelHistory, false, "BETA: Enable D3D12 pixel history support.");
`D3D12_PixelHistory` is fine for the config option - the `Debug` section is mostly for things like dumping verbose logs, intermediate files, etc. The top level is OK for chicken bits and it doesn't have to be moved even if we make it unavailable in stable builds (which I'd agree with for now).

2023-12-11 16:50 UTC, Zorro666 approved these changes

2023-12-11 21:33 UTC, skarolewics commented on renderdoc/driver/d3d12/d3d12_replay.cpp
> +RDOC_CONFIG(bool, D3D12_PixelHistory, false, "BETA: Enable D3D12 pixel history support.");
Should I still switch it to `RDOC_DEBUG_CONFIG`?

2023-12-12 08:47 UTC, Zorro666 commented on renderdoc/driver/d3d12/d3d12_replay.cpp
> +RDOC_CONFIG(bool, D3D12_PixelHistory, false, "BETA: Enable D3D12 pixel history support.");
I will do it after merging - seems simpler and don't want to waste your time on a small nitpick.

2023-12-12 08:47 UTC, merged