GL ELEMENT_ARRAY_BUFFER_BINDING issue not working for VAO == 0
baldurk/renderdoc pull request #3194
Opened 2023-12-31 19:46 UTC by Slaw6820

For array == 0 previous value should be restored instead of NULL assignment.

2024-01-02 12:26 UTC, Zorro666 requested changes
Hi

Thank you for the proposed fix. 

Can you explain what problem you discovered and if possible share a program that recreates the problem?

Looking at the GL spec the implemented behaviour looks correct, an `array` value of zero should break the current VAO binding i.e.

`glBindVertexArray binds the vertex array object with name array. array is the name of a vertex array object previously returned from a call to glGenVertexArrays, or zero to break the existing vertex array object binding.`

2024-01-02 12:34 UTC, Slaw6820 commented
It is an issue I have encountered some time ago while working on app I cannot share. I haven't looked into spec, but it seems like VAO == 0 had some data bound. If missing this fix, the some geometry was not rendered at all.

2024-01-02 14:03 UTC, Zorro666 commented
Thank you for explaining your use case. Not a problem about not being able to share the application.
Do you happen to know what API (GL or GLES) it was using and which version of the API.
The GL specification I mentioned is for GL Core and the behaviour of `glBindVertexArray` is different in other versions of GL

2024-01-02 16:14 UTC, Slaw6820 commented
I'm almost sure it was GL 4.6 Compatibility

2024-01-03 11:39 UTC, Zorro666 commented
GL Compatibility makes sense : the behaviour of the implementation needs to be different when capturing GL Core or not.

GL Core behaves as the code is currently and for GLES & Compatibility it needs to be changed to something like you have in this PR.

2024-01-03 16:52 UTC, Slaw6820 commented
Sure. So, does the fix fit here? Renderdoc supports GL core mainly, right?
If yes, how would you like to see this fix to be implemented?

2024-01-04 07:27 UTC, Zorro666 commented
I was thinking about this and this would be easier if there was an issue i.e. bug report which would give a reproduction case to work through. I would say we need to keep the previous and the new code but with an if test. The if test should only use the old code on a core profile (or the if test can be inverted and use the new code for GLES and Compatibility)

I think it would be useful to have a GL test program that uses this feature and the GL test program can run in Core or Compatibility mode to show the two different code paths, ideally there would also be a GLES test program.

I don't think there is a major rush on this change (as there is no bug report to work from). 
Let me look around for some GL test programs which could be used to verify the change. 
I will also look for the best way to do the if check.

2024-01-08 07:34 UTC, Zorro666 commented
I have been investigating to find a way to do this without an if test, which should be possible.
The problem I am having is not having a reproduction case for the particular problem that you discovered to validate any change and then not being able to understand what is needed to be fixed. The correct fix might be this PR or it might be a smaller version or the fix might be in a different piece of code.

I have been using the [gl_vao_0](https://github.com/baldurk/renderdoc/blob/v1.x/util/test/demos/gl/gl_vao_0.cpp) test program, however so far I have not been able to create any problems when calling `glBindVertexArray(0)`

If you were able to start from that test program (or a different reproduction project) to create a capture that does not replay correctly then we can move forward with the PR to identify and understand the problem and be able to verify the required fix.

2024-02-08 14:52 UTC, Zorro666 commented
Hi

Closing the PR as it has been a month without any replies.
There looks to be a valid problem here but without a reproduction case then the correct code fix can't be identified.

2024-02-08 14:52 UTC, closed without merging