Fix `vkEnumeratePhysicalDeviceGroups` being non-conformant with Vulkan specification
baldurk/renderdoc pull request #3262
Opened 2024-02-28 10:43 UTC by KacperZielinski-Intel

Fix for #3261

## Description

RenderDoc's `vkEnumeratePhysicalDeviceGroups` implementation was non-compliant with Vulkan specification.

When `vkEnumeratePhysicalDeviceGroups` has been called to query less than the total number of available device groups, then `pPhysicalDeviceGroupCount` parameter was overridden with the total amount of available device groups. However, Vulkan specification says that the amount of device groups written to `pPhysicalDeviceGroupProperties` should be returned instead.

In such cases, this was causing Vulkan loader (`vulkan-1.dll`) to crash on preparing `vkEnumeratePhysicalDeviceGroups` trampoline.

To fix this issue, I have reworked `vkEnumeratePhysicalDeviceGroups` implementation to be Vulkan specification compliant. I have also made some improvements, like early exit and replacement of raw memory management with `rdcarray` container.

2024-02-28 13:10 UTC, baldurk requested changes
Unless I'm missing something I think there's a different problem with the new code. From reading your description, it seems like a simpler commit to only change:

```
  if(pPhysicalDeviceGroupCount)
    *pPhysicalDeviceGroupCount = RDCMIN(outputSpace, numPhys);
```

Would fix the problem? Since the array handling is fine we just don't clamp the returned output count to the space given by the application.

As a side note - there's no requirement to open an issue for a bug if you have a PR to immediately close it, it's fine to open the PR directly and explain the issue as you have done.

2024-02-28 13:10 UTC, baldurk commented on renderdoc/driver/vulkan/wrappers/vk_get_funcs.cpp
> +      *pPhysicalDeviceGroupCount = physicalDevicesNumber;
Since this count is only written when the properties array is NULL, doesn't that mean that if someone calls the enumerate function with a large array & count then the count value won't get updated with the actual number of devices written? Sort of the reverse problem of the existing bug.

E.g.

```
VkPhysicalDeviceGroupProperties props[10];
uint32_t count = 10;
vkEnumeratePhysicalDeviceGroups(inst, &count, props);
// props[0] and props[1] may be filled out but count will still be 10 instead of 2
```

2024-02-28 15:29 UTC, KacperZielinski-Intel commented on renderdoc/driver/vulkan/wrappers/vk_get_funcs.cpp
> +      *pPhysicalDeviceGroupCount = physicalDevicesNumber;
You're right, I forgot to limit requested physical device **groups** number to the total number of physical devices.

[Vulkan documentation](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkEnumeratePhysicalDeviceGroups.html) requires `vkEnumeratePhysicalDeviceGroups` to return actual number of written physical device group properties in `pPhysicalDeviceGroupCount` (when `pPhysicalDeviceGroupProperties == NULL`).

I have pushed corrections.

2024-02-28 15:42 UTC, KacperZielinski-Intel commented
> Unless I'm missing something I think there's a different problem with the new code. From reading your description, it seems like a simpler commit to only change:
> 
> ```
>   if(pPhysicalDeviceGroupCount)
>     *pPhysicalDeviceGroupCount = RDCMIN(outputSpace, numPhys);
> ```
> 
> Would fix the problem? Since the array handling is fine we just don't clamp the returned output count to the space given by the application.

We cannot apply such a simple fix to the old code, as it don't differentiate cases of possible `pPhysicalDeviceGroupCount` return  values:
- total number of available device groups; when `pPhysicalDeviceGroupProperties == NULL`
- actual number of written physical device groups; when `pPhysicalDeviceGroupProperties != NULL`

I insist on merging this fix with my other changes to `vkEnumeratePhysicalDeviceGroups` function.
Nevertheless, if you don't like style of my changes, I can try to just emplace fix in original function body.

2024-03-05 16:45 UTC, baldurk commented
Ah OK I see what you mean, yes it needs more than the one line fix. I was just trying to clarify which of the changes are necessary or not, as generally speaking a simpler fix is preferable, I wasn't suggesting that I would reject the fix entirely.

2024-03-05 16:45 UTC, merged