SPIRV debug mapping updates to handle multiple overlapping mappings Issue #3264
baldurk/renderdoc pull request #3294
Opened 2024-04-11 17:09 UTC by Zorro666

## Description
- Capture the mappings into a type usage tree
- Update elements of the tree as overlapping mappings are encountered, sub-elements of a previously mapped variable i.e. single component of a vector, single array element, member in a structure.
- After processing all mappings convert the finalized type usage tree into source variable mappings.
- Fixed bug in `LocalMapping::isSourceSupersetOf` where it would mis-identify a superset
- Update struct member and array element names of SPIRV constants
  - array names and struct member names are not set when constants are created (struct decoration data is not available)
  - Fixes problem with incorrect register names when using struct, array initialisers.

## Testing
- Test HLSL shader compiled using DXC, Slang, glslang
- Reproduction case in Issue #3264 

## Test HLSL Shader

[OpDebugValue.hlsl](https://github.com/baldurk/renderdoc/files/14949151/OpDebugValue.hlsl.txt)

```
struct v2f
{
    float4 pos : SV_POSITION;
    float4 col : COLOR0;
    float4 uv : TEXCOORD0;
};

struct Foo
{
    float f;
    int i;
};

struct Test
{
    float2 v2;
    float3 v3;
    float4 v4;
    column_major float2x3 m23; // 2 rows, 3 columns
    column_major float3x2 m32; // 3 rows, 2 columns
    float4x4 m44; // 4 rows, 4 columns
    int i;
    uint a[10];
    Foo nested;
    Foo nested_array[4];
};

struct TestTwo
{
    float2 v2;
    float3 v3;
    float4 v4;
};

Test TestValue(float fValue)
{
    Test test;
    test.v2.x = fValue;
    fValue += 1.0;
    test.v2.y = fValue;
    fValue += 1.0;

    test.v3.x = fValue;
    fValue += 1.0;
    test.v3.y = fValue;
    fValue += 1.0;
    test.v3.z = fValue;
    fValue += 1.0;

    test.v4.x = fValue;
    fValue += 1.0;
    test.v4.y = fValue;
    fValue += 1.0;
    test.v4.z = fValue;
    fValue += 1.0;
    test.v4.w = fValue;
    fValue += 1.0;

    // 2 rows, 3 columns
    test.m23[0].x = fValue;
    fValue += 1.0;
    test.m23[0].y = fValue;
    fValue += 1.0;
    test.m23[0].z = fValue;
    fValue += 1.0;

    test.m23[1].x = fValue;
    fValue += 1.0;
    test.m23[1].y = fValue;
    fValue += 1.0;
    test.m23[1].z = fValue;
    fValue += 1.0;

    // 3 rows, 2 columns
    test.m32[0].x = fValue;
    fValue += 1.0;
    test.m32[0].y = fValue;
    fValue += 1.0;

    test.m32[1].x = fValue;
    fValue += 1.0;
    test.m32[1].y = fValue;
    fValue += 1.0;

    test.m32[2].x = fValue;
    fValue += 1.0;
    test.m32[2].y = fValue;
    fValue += 1.0;

    // 4 rows, 4 columns
    test.m44[0].x = fValue;
    fValue += 1.0;
    test.m44[0].y = fValue;
    fValue += 1.0;
    test.m44[0].z = fValue;
    fValue += 1.0;
    test.m44[0].w = fValue;
    fValue += 1.0;

    test.m44[1].x = fValue;
    fValue += 1.0;
    test.m44[1].y = fValue;
    fValue += 1.0;
    test.m44[1].z = fValue;
    fValue += 1.0;
    test.m44[1].w = fValue;
    fValue += 1.0;

    test.m44[2].x = fValue;
    fValue += 1.0;
    test.m44[2].y = fValue;
    fValue += 1.0;
    test.m44[2].z = fValue;
    fValue += 1.0;
    test.m44[2].w = fValue;
    fValue += 1.0;

    test.m44[3].x = fValue;
    fValue += 1.0;
    test.m44[3].y = fValue;
    fValue += 1.0;
    test.m44[3].z = fValue;
    fValue += 1.0;
    test.m44[3].w = fValue;
    fValue += 1.0;

    test.i = (int) fValue;
    fValue += 1.0;

    test.a[0] = (int) fValue;
    fValue += 1.0;
    test.a[1] = (int) fValue;
    fValue += 1.0;
    test.a[2] = (int) fValue;
    fValue += 1.0;
    test.a[3] = (int) fValue;
    fValue += 1.0;
    test.a[4] = (int) fValue;
    fValue += 1.0;
    test.a[5] = (int) fValue;
    fValue += 1.0;
    test.a[6] = (int) fValue;
    fValue += 1.0;
    test.a[7] = (int) fValue;
    fValue += 1.0;
    test.a[8] = (int) fValue;
    fValue += 1.0;
    test.a[9] = (int) fValue;
    fValue += 1.0;

    test.nested.f = fValue;
    fValue += 1.0;
    test.nested.i = (int) fValue;

    test.nested_array[0].f = fValue;
    fValue += 1.0;
    test.nested_array[0].i = (int) fValue;
    fValue += 1.0;
    test.nested_array[1].f = fValue;
    fValue += 1.0;
    test.nested_array[1].i = (int) fValue;
    fValue += 1.0;
    test.nested_array[2].f = fValue;
    fValue += 1.0;
    test.nested_array[2].i = (int) fValue;
    fValue += 1.0;
    test.nested_array[3].f = fValue;
    fValue += 1.0;
    test.nested_array[3].i = (int) fValue;
    fValue += 1.0;

    return test;
}

float TestHash(Test test)
{
    float fValue = 0.0;

    fValue += test.v2.x;
    fValue += test.v2.y;

    fValue += test.v3.x;
    fValue += test.v3.y;
    fValue += test.v3.z;

    fValue += test.v4.x;
    fValue += test.v4.y;
    fValue += test.v4.z;
    fValue += test.v4.w;

    // 2 rows, 3 columns
    fValue += test.m23[0].x;
    fValue += test.m23[0].y;
    fValue += test.m23[0].z;

    fValue += test.m23[1].x;
    fValue += test.m23[1].y;
    fValue += test.m23[1].z;

    // 3 rows, 2 columns
    fValue += test.m32[0].x;
    fValue += test.m32[0].y;

    fValue += test.m32[1].x;
    fValue += test.m32[1].y;

    fValue += test.m32[2].x;
    fValue += test.m32[2].y;

    // 4 rows, 4 columns
    fValue += test.m44[0].x;
    fValue += test.m44[0].y;
    fValue += test.m44[0].z;
    fValue += test.m44[0].w;

    fValue += test.m44[1].x;
    fValue += test.m44[1].y;
    fValue += test.m44[1].z;
    fValue += test.m44[1].w;

    fValue += test.m44[2].x;
    fValue += test.m44[2].y;
    fValue += test.m44[2].z;
    fValue += test.m44[2].w;

    fValue += test.m44[3].x;
    fValue += test.m44[3].y;
    fValue += test.m44[3].z;
    fValue += test.m44[3].w;

    fValue += (float) test.i;

    fValue += test.a[0];
    fValue += test.a[1];
    fValue += test.a[2];
    fValue += test.a[3];
    fValue += test.a[4];
    fValue += test.a[5];
    fValue += test.a[6];
    fValue += test.a[7];
    fValue += test.a[8];
    fValue += test.a[9];

    fValue += test.nested.f;
    fValue += (float) test.nested.i;

    fValue += test.nested_array[0].f;
    fValue += (float) test.nested_array[0].i;
    fValue += test.nested_array[1].f;
    fValue += (float) test.nested_array[1].i;
    fValue += test.nested_array[2].f;
    fValue += (float) test.nested_array[2].i;
    fValue += test.nested_array[3].f;
    fValue += (float) test.nested_array[3].i;

    return fValue;
}

Foo FooValue(float fValue)
{
    Foo foo;
    int iValue = (int) fValue;
    foo.f = fValue;
    foo.i = iValue;;
    return foo;
}

float Test1()
{
    // Test various mappings directly at different granularities:
    // Just one mapping for Test, not overridden
    Test test1 = (Test) 0;
    return TestHash(test1);
}

float Test2()
{
    Foo fooZero = (Foo) 0;
    // Map only Test::i and Test::nested, none of the other members
    Test test2;
    test2.i = 123;
    test2.nested = fooZero;

    test2 = (Test) 0;

    return TestHash(test2);
}

float Test3()
{
    uint test_a[10] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
    Foo test_nested_array[4] =
    {
        { 1.0, -1 },
        { 2.0, -2 },
        { 3.0, -3 },
        { 4.0, -4 }
    };

    // Non-overlapping mappings for all of Test's direct child members 1:1
    Test test3;
    test3.v2 = (float2) 2.0;
    test3.v3 = (float3) 3.0;
    test3.v4 = (float4) 4.0;
    test3.m23 = (float2x3) 5.0;
    test3.m32 = (float3x2) 6.0;
    test3.m44 = (float4x4) 7.0;
    test3.i = 321;
    test3.a = test_a;
    test3.nested = test_nested_array[2];
    test3.nested_array = test_nested_array;

    return TestHash(test3);
}

float Test4()
{
  // Non-overlapping mappings for every scalar value (e.g. down to Test::a[0] mapped separately from Test::a[1])
    Test test4;

    test4.v2.x = 1.0;
    test4.v2.y = 2.0;

    test4.v3.x = 3.0;
    test4.v3.y = 4.0;
    test4.v3.z = 5.0;

    test4.v4.x = 6.0;
    test4.v4.y = 7.0;
    test4.v4.z = 8.0;
    test4.v4.w = 9.0;

    test4.m23[0].x = 500.0;
    test4.m23[0].y = 501.0;
    test4.m23[0].z = 502.0;

    test4.m23[1].x = 503.0;
    test4.m23[1].y = 504.0;
    test4.m23[1].z = 505.0;

    test4.m32[0].x = 506.0;
    test4.m3 [...]

2024-04-11 17:13 UTC, Zorro666 commented on renderdoc/driver/shaders/spirv/spirv_debug_setup.cpp
> +              RDCASSERT(col < columns, col, columns);
Should this be more than an assert as if the assert fires it will read  off the end of the array.

Could reserve the matrix arrays to 4x4 to make sure there is enough space

2024-04-13 15:13 UTC, Zorro666 commented on renderdoc/driver/shaders/spirv/spirv_debug_setup.cpp
> +        if(n->columnMajor)
This is not tested or verified and matches the existing code.
`DXC` / `glslang` do not generate `DebugTypeMatrix` instructions
`slang` does generate `DebugTypeMatrix` instruction but I am not sure `slang` generation is correct.

2024-04-16 15:01 UTC, baldurk requested changes

2024-04-16 15:01 UTC, baldurk commented on renderdoc/driver/shaders/spirv/spirv_debug.h
> +    // the indexes are in reverse order (they are used back to front)
Probably a good idea to leave a comment on the `indexes` array or maybe just rename it to `indexRevOrder` or something to ensure there's no confusion in future - given that I'd forgotten we stored these back to front..

2024-04-16 15:01 UTC, baldurk commented on renderdoc/driver/shaders/spirv/spirv_debug_setup.cpp
> +    for(size_t i = 0; i < c.members.size(); ++i)
Maybe an assert that `c.members.size() == typeWalk->children.size()` here, and below for the array? It should always be true but just in case it breaks it would make a crash here easier to figure out.

2024-04-16 15:01 UTC, baldurk commented on renderdoc/driver/shaders/spirv/spirv_debug_setup.cpp
> +      rdcstr regSuffix;
I deliberately moved away from 'register' type naming which is DXBC specific, so I think this should be `debugVarSuffix`.

2024-04-16 15:01 UTC, baldurk commented on renderdoc/driver/shaders/spirv/spirv_debug_setup.cpp
> +        sourceVar.offset = 0;
This is redundant - offset is set properly just below.

2024-04-16 15:01 UTC, baldurk commented on renderdoc/driver/shaders/spirv/spirv_debug_setup.cpp
> +    struct Node
I think the structure here and the algorithm below could do with a broader comment to explain the principle - that we repeatedly apply mappings, allowing them to fully or partially override. When they fully override we consolidate and remove any previous splits, and if they partially override then we break up the current mapping to preserve what remains still valid and then overwrite with the new mapping contents.

2024-04-16 15:01 UTC, baldurk commented on renderdoc/driver/shaders/spirv/spirv_debug_setup.cpp
> +              rdcarray<uint32_t> dims = typeWalk->arrayDimensions;
const ref here just to save a copy.

2024-04-22 11:52 UTC, baldurk approved these changes

2024-04-22 11:52 UTC, merged