Added ability to save out overlay textures using the TextureSaveDialog.
baldurk/renderdoc pull request #824
Opened 2017-12-14 03:43 UTC by rkhoury

This is part of the work specified by github Issue 586, allowing the
ability to save out the overlay in the TextureViewer.  If no overlays
are on then there is no option to save the overlay. Currently there is
no option to remap the overlay to a grayscale or absolute value range
before saving. This can be a future task.

NOTE: the overlay texture resource that's saved out is not the blended
texture that the user will see in the TextureViewer, it is just the
overlay itself. The ability to save out the blended texture would be a
future task.

2017-12-14 11:23 UTC, baldurk requested changes
This looks good, I've made a couple of minor comments on the code.

I've fixed the CI issues on v1.x now, so when you fix those if you rebase onto HEAD again it should be a known good version.

2017-12-14 11:23 UTC, baldurk commented on qrenderdoc/Windows/TextureViewer.cpp
> +  const auto overlayTexID = m_Output->GetDebugOverlayTexID();
No `auto` please unless the type is really horrible like an iterator or lambda, `ResourceId` is preferred here :smile:.

2017-12-14 11:23 UTC, baldurk commented on qrenderdoc/Windows/TextureViewer.cpp
> +  const bool hasSelectedOverlay = (m_Output->GetTextureDisplay().overlay != DebugOverlay::NoOverlay);
I'd prefer not to add a query function like `GetTextureDisplay` when the information should be available already. Can you just use `m_TexDisplay` here?

2017-12-14 11:37 UTC, rkhoury commented on qrenderdoc/Windows/TextureViewer.cpp
> +  const auto overlayTexID = m_Output->GetDebugOverlayTexID();
No worries - I'm happy to make this change.  I tend to use auto when I can easily see the definition implied by assignment (it's use is within 5 lines of code or so).

2017-12-14 11:38 UTC, rkhoury commented on qrenderdoc/Windows/TextureViewer.cpp
> +  const bool hasSelectedOverlay = (m_Output->GetTextureDisplay().overlay != DebugOverlay::NoOverlay);
Oh man!! I totally didn't see that member. The joys of learning a new codebase...

2017-12-15 12:11 UTC, baldurk approved these changes

2017-12-15 12:20 UTC, merged